
services:
  db:
    image: mysql:8.0
    container_name: online-food-db
    restart: always
    environment:
      MYSQL_DATABASE: online-food-database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - online-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: online-food-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/online-food-database?
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy # wait for MySQL to pass healthcheck
    ports:
      - "8083:8080"
    networks:
      - online-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: online-food-frontend
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - online-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
